_american = 0;
_russian = 0;



OPFL_AMERICAN_TICKETS = OPFL_STARTING_TICKETS;
OPFL_RUSSIAN_TICKETS = OPFL_STARTING_TICKETS;

publicVariable "OPFL_AMERICAN_TICKETS";
publicVariable "OPFL_RUSSIAN_TICKETS";