private "_scripts";
private "_CompileFolder";

_scripts = 
[


["GSC", "PUBLIC_CODE_SYSTEM\GLOBAL_SC_SCRIPTS"],
["PCS", "PUBLIC_CODE_SYSTEM\CONVERSIONS"],
["PCS", "PUBLIC_CODE_SYSTEM\CLIENT_RECV_SYSTEM"],
["PCS", "PUBLIC_CODE_SYSTEM\CALL_EXTENSION"],
["PCS", "PUBLIC_CODE_SYSTEM"],
["VRS", "PUBLIC_CODE_SYSTEM\VEHICLE_RESPAWN_SYSTEM"],
["VRS", "PUBLIC_CODE_SYSTEM\VEHICLE_RESPAWN_SYSTEM\USER_FUNCTIONS"],
["PCS_RNK", "PUBLIC_CODE_SYSTEM\RANK_MODULE"],
["PCS_SHOP", "PUBLIC_CODE_SYSTEM\RANK_MODULE\SHOP"]
];
_CompileFolder = compile PreProcessFile "PUBLIC_CODE_SYSTEM\CompileFolder.sqf";
{
	_null = _x call _CompileFolder;
} foreach _scripts;

PCS_ALL_SCRIPTS_COMPILED = true;