private "_scripts";
private "_CompileFolder";

_scripts = 
[
["PKS", "PLAYER_KITS"],
["PKS", "PLAYER_KITS\WEST"],
["PKS", "PLAYER_KITS\EAST"],
["PKS", "PLAYER_KITS\SPECIAL_WEAPONS"],
["PKS", "PLAYER_KITS\SPECIAL_WEAPONS\ACTIONS"],
["EMP", "PLAYER_KITS\SPECIAL_WEAPONS\EMP\EMP_GUI_SCRIPTS"],
["EMP", "PLAYER_KITS\SPECIAL_WEAPONS\EMP"],
["PKS", "PLAYER_KITS\GUI_SCRIPTS"],
["PKS_ServerBS", "PLAYER_KITS\BUILD_SYSTEM\SERVER_BUILD_SYSTEM"],
["PKS_ClientBS", "PLAYER_KITS\BUILD_SYSTEM\CLIENT_BUILD_SYSTEM"]
];
_CompileFolder = compile PreProcessFile "PLAYER_KITS\CompileFolder.sqf";
{
	_null = _x call _CompileFolder;
} foreach _scripts;

PKS_ALL_SCRIPTS_COMPILED = true;