//list of scripts to compile
_folderScripts = ["LoadKits",
			"FillKit",
			//"SelectKit",
			//"SetKit",
			"AttachKit",
			"KitActionUpdater",
			"DropKit",
			//"InitPlayerKits",
			"ServerKitThread",
			"ServerKitQueue",
			//"DisconnectKit",
			"ClientKitThread",
			"ClientKitQueue",
			"RequestFillKit",
			"AddMedicAction",
			"AddRepairAction",
			"GetKitData",
			"GetKitIndices",
			"ProcessKits",
			"AttemptDisconnectKit",
			"RequestSetKit",
			"GetKitDescription",
			"RejectWeapon",
			"Parameters",
			"ChangeWeapons",
			"GetPossibleLinkedItems",
			"Armory_Object"];
			
//return list			
_folderScripts;