//list of scripts to compile
_folderScripts = ["CreateSpawnProtectors",
		  	"DelayLock",
		  	"EqualPosArrays",
		  	"FormatTime",
		  	"PlayerSquad",
		  	"RandPosAroundObject",
		  	"CreateHotZones",
		  	"2dDistance",
		  	"IsDisabled",
		  	"PVRepair",
		  	"InSafeZone",
		  	"UsedVehicle",
		  	"InEnemySafeZone",
		  	"IsColliding",
		  	"LockVehicleClasses",
		  	"UnlockVehicleClasses",
		  	"DrawMarkerConnection",
		  	"OverEZW",
		  	"RotateField",
		  	"FrontLineFlag",
		  	"AxisIntersectPoint",
		  	"FieldWidth",
		  	"ValidFBP",
		  	"PolarVector",
			"HighestSurface",
			"IsCarrier",
			"ToSteep",
			"EnableSZP",
			"FrameRate",
			"CreateSound",
			"PlaySound",
			"PolarToCartesian",
			"Side",
			"Name",
			"GetDamage",
			"FindReplaceString",
			"CreateRandomKey",
			"CompressKey",
			"MapKeyToVarName"];
			
//return list			
_folderScripts;